### PR TITLE
Crew Credits Antagonists Tab

### LINKED ISSUE #15870: Thralls don't show up as antags in the credits
### Labels

[BUG]

### Description

title, they don't show up

### Steps to reproduce

1. be thralled
2. round ends
3. ur not there

i kinda get it because it's a temp antag technically, but confusing

### Expected Behavior

i expected to show up

### Additional Information & Screenshots

@Mister-Moriarty ?

### PR DESCRIPTION
**Pull request by Mister-Moriarty**
[UI] [QoL]

## About The PR:
Implements an antagonists tab to the end of round crew credits, displaying details regarding each major antagonist of the round, including their antagonist roles; job; status; objectives; general statistics, such as purchased equipment or blood drank; and their subordinate antagonists.

Antagonists not considered major, such as subordinate antagonists, generic antagonists, or revolutionaries will be displayed under the "Other Antagonists" section. If a subordinate antagonist has a master, they will instead be listed under their master's data entry.

image

Additionally to better facilitate a tab oriented structure, the crew credits datum has been refactored.

## Why Is This Needed?
Deprecates the old text window readout of antagonist statistics, and therefore fixes #15870.

## Changelog:
```changelog
(u)Mr. Moriarty
(*)Added an antagonists tab to the end of round crew credits.
```

### CODE REVIEW

**Comment by 444Portal** [comment]
Hell yeah! Looks great.

File: tgui/packages/tgui/interfaces/CrewCredits/AntagonistsTab.tsx [hunk 1]
```diff
@@ -0,0 +1,251 @@
...
+            mb={-2.5}
+            italic>
+            The Game Mode Was:
+          </Stack.Item>
+          <Stack.Item
+            fontSize={2.75}
+            bold>
+            {data.game_mode}
+          </Stack.Item>
+        </Stack>
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/CrewCredits/AntagonistsTab.tsx:33]: Slice this out into its own component, there's a lot of presentation information here that adds unnecessary complexity to reading the parent component to show what's actually just `<GameModeDisplay>{data.game_mode}</GameModeDisplay>`

File: tgui/packages/tgui/interfaces/CrewCredits/AntagonistsTab.tsx [hunk 2]
```diff
@@ -0,0 +1,251 @@
...
+          key={index}
+          antagonist_roles={antagonist.antagonist_roles}
+          real_name={antagonist.real_name}
+          player={antagonist.player}
+          job_role={antagonist.job_role}
+          status={antagonist.status}
+          objectives={antagonist.objectives}
+          antagonist_statistics={antagonist.antagonist_statistics}
+          subordinate_antagonists={antagonist.subordinate_antagonists}
+        />)
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/CrewCredits/AntagonistsTab.tsx:46]: Not confirmed the data types match entirely, but you can probably just do:
```suggestion
        (<Antagonist
          key={index}
          {...antagonist}
        />)
```

File: tgui/packages/tgui/interfaces/CrewCredits/CrewTab.tsx [hunk 3]
```diff
@@ -1,38 +1,27 @@
 /**
  * @file
  * @copyright 2023
- * @author glowbold (https://github.com/pgmzeta)
+ * @author Original glowbold (https://github.com/pgmzeta)
+ * @author Changes Mr. Moriarty (https://github.com/Mister-Moriarty)
  * @license MIT
- */
+*/
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/CrewCredits/CrewTab.tsx:7]:
```suggestion
 */
```

**Review by mordent-goonstation — CHANGES_REQUESTED** [review]

File: tgui/packages/tgui/components/goonstation/ItemList.tsx [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+          />
+        </Flex.Item>
+      )}
+      <Flex.Item
+        pr={1}
+        pl={0.5}>
+        {item.name}
+        {`${index === arr.length - 1 ? '' : `, ${index === arr.length - 2 ? 'and ' : ''}`}`}
+      </Flex.Item>
+    </Flex>
```
[the remark this answers is not in the document]
Comment (Mister-Moriarty) [reply tgui/packages/tgui/components/goonstation/ItemList.tsx:42]: I'm using `Flex` so to avoid spacing other than where explicitly stated.

File: tgui/packages/tgui/components/goonstation/ItemList.tsx [hunk 5]
```diff
@@ -0,0 +1,54 @@
+/**
+ * @file
+ * @copyright 2021
+ * @author Mordent (https://github.com/mordent-goonstation)
+ * @license ISC
+ */
+
+import { Flex, Image } from '..';
+
+export const ItemList = (props: ItemListProps) => {
```
[the remark this answers is not in the document]
Comment (Mister-Moriarty) [reply tgui/packages/tgui/components/goonstation/ItemList.tsx:10]: I would rather have `ItemList` be located in the common components list; in order to pull it out of the crew credits folder, and individual first has to know it is located there, whereas when in the common list, it is more visible to UI coders, and as a result is more likely to be used.

**Comment by Mister-Moriarty** [comment]
Thank you kindly for the UI review!

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
Overall looks great! Thanks for doing this, have some nitpicks:

File: code/datums/mind.dm [hunk 6]
```diff
@@ -26,6 +26,8 @@ datum/mind
 
 	/// A list of every antagonist datum that we have.
 	var/list/datum/antagonist/antagonists = list()
+	/// A list of every antagonist datum subordinate to this mind.
+	var/list/datum/antagonist/subordinate/subordinate_antagonists = list()
```
[the remark this answers is not in the document]
Comment (Mister-Moriarty) [reply code/datums/mind.dm:30]: Subordinate antagonists track their master's mind directly.

**Comment by TobleroneSwordfish** [comment]
Some things are definitely not rendering right in the stolen items section:
image

**Comment by flappybatpal** [comment]
Could be nice if you could click the antag in General and it would take you over to them in Antagonists.

**Comment by mordent-goonstation** [comment]
> Some things are definitely not rendering right in the stolen items section: image

Looks like it's sending up all four directions (or the entire spritesheet?) of it or something?

File: code/modules/antagonists/spy_thief/spy_thief.dm [hunk 7]
```diff
@@ -108,31 +108,41 @@
...
 		if (length(src.stolen_items) >= 7)
 			src.owner.current.unlock_medal("Professional thief", TRUE)
 
-		return dat
+	get_statistics()
+		var/list/stolen_items = list()
+		for (var/obj/stolen_item as anything in src.stolen_items)
+			stolen_items += list(
+				list(
+					"iconBase64" = "[icon2base64(icon(initial(stolen_item.icon), initial(stolen_item.icon_state), frame = 1))]",
```
Comment (TobleroneSwordfish) [inline code/modules/antagonists/spy_thief/spy_thief.dm:122]:
```suggestion
					"iconBase64" = "[icon2base64(icon(initial(stolen_item.icon), initial(stolen_item.icon_state), frame = 1, dir = initial(stolen_item.dir)))]",
```
I think this is it, might do strange things with items but probably not?

**Comment by Mister-Moriarty** [comment]
> Once the server starts restarting, can you still switch tabs and expand/collapse sections?

You may, yes, from what I have tested on the live servers.

**Comment by TobleroneSwordfish** [comment]
Testmerge updated 👍

**Comment by amylizzle** [comment]
This seems to be already reported, but still 
image
