### PR TITLE
Player Zoldorf Shop TGUI

### LINKED ISSUE #17781: Occupuied zoldorf booth's UI is broken
### Labels

[BUG][MAJOR]

### Description

Clicking on an occuopied zoldorf brings up a white screen with the lines "soul items" and "credit items". No items can be seen or bought

### Steps to reproduce

Occupy a zoldorf booth
Have someone click on it

### Expected Behavior

for the vendor menu to show up

### Additional Information & Screenshots

Reported by: Lopz1
On server: Goonstation 3 Roleplay: Morty
Active test merges: #17577 and #17478
Round log date: 2024-01-26-14-33
Reported on: 2024-01-26 14:52:09
Map: COGMAP

### PR DESCRIPTION
**Pull request by pgmzeta**
[UI][GAME OBJECTS][BUG]
## About the PR 
* Adds a new interface for the Player-controlled Zoldorf machine, mimicing the current Vending Machine TGUI layout
* Separates products into two different subtypes of `/datum/zoldorfitem`, based on whether it costs soul or credit
* Removes no longer needed zoldorf `Topic`, `browserassets`, and related world preload

## Why's this needed? 
Interface is completely broken currently
Fixes #17781

## Screenshots
Left is the regular (unchanged) vending machine interface, right is the new Player-Zoldorf interface.
### Light Mode
Screenshot 2024-03-26 121631

### Dark Mode
Screenshot 2024-03-26 121649

## Changelog 

```changelog
(u)glowbold
(*)Playerdorfs may once again vie for the souls of the living.
```

### CODE REVIEW

**Review by Tarmunora — APPROVED** [review]

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+        <Stack vertical fill minHeight="1%" maxHeight="100%">
+          <Stack.Item grow minHeight="1%" maxHeight="100%">
+            <Stack vertical>
+              {
+                soul_products.map(product => {
+                  return (
+                    <ZoldorfProductList {...product} key={product.name}>
+                      <Button
+                        color="red"
+                        onClick={() => act('soul_purchase', { "item": product.name })}
```
Comment (mloccy) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx:32]: Would be nice if buttons were uniform in size
image

**Review by mloccy — COMMENTED** [review]
Nice to see zoldorf get some love.

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+          { credits !== 0 && (
+            <Stack.Item>
+              <Table>
+                <Table.Row>
+                  <Table.Cell bold direction="row">
+                    {("Cash: " + credits + "⪽")}
+                    <Button
+                      icon="eject"
+                      ml="1%"
+                      content={"eject"}
```
Comment (mloccy) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx:71]:
```suggestion
                      content={"Eject"}
```

**Review by mloccy — APPROVED** [review]
LGTM

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx (hunk 2 above)
Comment (pgmzeta) [reply tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx:71]: the regular vending machine interface uses lowercase and I prefer to match that

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+  return (
+    <Window
+      width="500"
+      height="600"
+      fontFamily="Consolas"
+      font-size="10pt">
+      <Window.Content>
+        <Stack vertical fill minHeight="1%" maxHeight="100%">
+          <Stack.Item grow minHeight="1%" maxHeight="100%">
+            <Section fill scrollable height="100%">
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx:25]: Going to have to explain all of the `1%`/`100%` things here. If these are just pulled from some other place (presumably vending machine code), please let me know where and I'll have to work out how to rewrite in a sane fashion.

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+                {
+                  soul_products.map(product => {
+                    return (
+                      <ZoldorfProductList {...product} key={product.name}>
+                        <Button
+                          color="red"
+                          disabled={product.soul_percentage > data.user_soul}
+                          onClick={() => act('soul_purchase', { "item": product.name })}
+                          style={{ "width": "50px", "text-align": "center", "padding": "0px" }}
+                          content={("" + product.soul_percentage + "%")}
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx:36]:
```suggestion
                          content={`${product.soul_percentage}%`}
```

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx [hunk 5]
```diff
@@ -0,0 +1,128 @@
...
+              </Stack>
+              <Stack vertical>
+                {
+                  credit_products.map(product => {
+                    return (
+                      <ZoldorfProductList {...product} key={product.name}>
+                        <Button
+                          color="green"
+                          disabled={product.price > credits}
+                          content={("" + product.price + "⪽")}
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx:51]:
```suggestion
                          content={`${product.price}⪽`}
```

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx [hunk 6]
```diff
@@ -0,0 +1,128 @@
...
+          </Stack.Item>
+          { credits !== 0 && (
+            <Stack.Item>
+              <Table>
+                <Table.Row>
+                  <Table.Cell bold direction="row">
+                    {("Cash: " + credits + "⪽")}
+                    <Button
+                      icon="eject"
+                      ml="1%"
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx:70]: Prefer static padding on the cell rather than percentage margin on the content.

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx [hunk 7]
```diff
@@ -0,0 +1,128 @@
...
+  } = props;
+  return (
+    <Flex justify="space-between" align="stretch" style={{ "border-bottom": "1px #555 solid" }}>
+      <Flex.Item direction="row">
+        {img && (
+          <Box style={{ "overflow": "show", "height": "24px" }}>
+            <img
+              src={`data:image/png;base64,${img}`}
+              style={{
+                'transform': 'translate(0, -4px)',
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx:101]: Presumably shunting for a reason?

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx [hunk 8]
```diff
@@ -0,0 +1,128 @@
...
+          "flex-direction": "column",
+        }}>
+        <Box>
+          <Box inline italic>
+            {!infinite && `${stock} x`}&nbsp;
+          </Box>
+          <Box inline>{name}</Box>
+        </Box>
+      </Flex.Item>
+      <Flex.Item bold direction="row" style={{ "margin-left": "5px",
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx:119]: Why do you need to change the `margin-left` here? i.e. what is wrong with base behavior? I'm not sure if `direction="row"` does anything here (it might do by virtue of being one of the properties that gets straight converted to a CSS property), but in either case is at odds with the `flex-direction: column;` set further down.

Is the goal is to center the items within each flex cell?

You probably want `align="center"` (for vertical centering) on the containing `Flex` at least, that should remove some of these style overrides.

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/type.ts [hunk 9]
```diff
@@ -0,0 +1,35 @@
...
+  soul_percentage: number,
+}
+
+export interface ZoldorfCreditProductData extends ZoldorfProductData {
+  price: number,
+}
+
+export interface ZoldorfProductListProps extends ZoldorfProductData {
+  children: InfernoNode,
+}
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/type.ts:35]: Likely overkill, but with as written I'm assuming the idea here is for these to be mutually exclusive? If so, let me know and I'll write an example of how to use union types in Typescript to help with it.

File: code/obj/zoldorf.dm [hunk 10]
```diff
@@ -85,6 +40,114 @@ var/global/list/datum/zoldorfitem/zoldorf_items = list()
 	New()
 		. = ..()
 		START_TRACKING
+		for(var/product in childrentypesof(/datum/zoldorfitem/soul))
+			src.soul_items += new product
+		for(var/product in childrentypesof(/datum/zoldorfitem/credit))
+			src.credit_items += new product
```
Comment (mordent-goonstation) [inline code/obj/zoldorf.dm:46]: Not verified this works, but possibly (takes advantage of abstract annotations):
```suggestion
		for(var/product in concrete_typesof(/datum/zoldorfitem))
			src.soul_items += new product
```

**Review by mordent-goonstation — CHANGES_REQUESTED** [review]

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/type.ts (hunk 9 above)
Comment (pgmzeta) [reply tgui/packages/tgui/interfaces/ZoldorfPlayerShop/type.ts:35]: Yes please, I would like to learn how to use union types here

Comment (mordent-goonstation) [reply tgui/packages/tgui/interfaces/ZoldorfPlayerShop/type.ts:35]: Pester me in Discord (`@mordent`) if I don't do this in the next few days.

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/type.ts [hunk 11]
```diff
@@ -7,24 +7,28 @@
...
 }
 
-export interface ZoldorfCreditProductData extends ZoldorfProductData {
+export interface ZoldorfCreditProductData extends ZoldorfCommonProductData {
   price: number;
 }
+
+export type ZoldorfProductData = ZoldorfSoulProductData | ZoldorfCreditProductData;
+
+export const isSoulProductData = (value: ZoldorfProductData): value is ZoldorfSoulProductData =>
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/type.ts:27]: Typeguard, used to determine whether a non-specific one is one of the specific ones or not. TS can use this to do correct typing if code logic can only go one way, e.g. an `if` statement or a ternary.

Comment (pgmzeta) [reply tgui/packages/tgui/interfaces/ZoldorfPlayerShop/type.ts:27]: Thank you for explaining how to tackle it this way.

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+}
+
+const ZoldorfProductListItem = (props: ZoldorfProductListItemProps) => {
+  const { name, img, stock, infinite, children } = props;
+  return (
+    <Flex
+      style={{
+        'align-items': 'center',
+        'border-bottom': '1px #555 solid',
+      }}>
```
[the remark this answers is not in the document]
Comment (pgmzeta) [reply tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx]: used a section as requested, but I feel like the current vending machines use a bottom border more as a left-to-right rule line since the purchase buttons are right-aligned.

[the remark this answers is not in the document]
Comment (mordent-goonstation) [reply tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx]: Fair I suppose. At this point we probably need to think about having "list of items with images and buttons" as a standard interface somewhere, but not needed for your PR.

I'm fine with you putting the border back in for the sake of UI consistency, apologies for back-and-forth on it.

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx [hunk 13]
```diff
@@ -0,0 +1,95 @@
...
+            position="relative" // don't increase line-height, but keep image size
+            height="20px" // 20 px height - 32 px sprite = -12 px of offset
+            top="-6px" // -12px / 2 = -6px top offset to keep them centered
+          >
+            {img && <Image pixelated src={`data:image/png;base64,${img}`} />}
+          </Box>
+        </Flex.Item>
+        <Flex.Item grow>
+          <>
+            <Box inline italic>{!infinite && `${stock} x\xa0`}</Box>
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx:85]: Prefer `&nbsp;` to `\xa0`.

File: code/obj/zoldorf.dm [hunk 14]
```diff
@@ -71,6 +23,9 @@ var/global/list/datum/zoldorfitem/zoldorf_items = list()
 	var/omen
 	var/occupied
 
+	var/list/datum/zoldorfitem/soul/soul_items = list()
+	var/list/datum/zoldorfitem/credit/credit_items = list()
```
Comment (mordent-goonstation) [inline code/obj/zoldorf.dm:27]:
```
	var/list/datum/zoldorfitem/soul/soul_items = null
	var/list/datum/zoldorfitem/credit/credit_items = null
```
Then instantiate the lists in `New()`. Minor and especially so given the fact that this isn't made frequently, but code standard are code standards. I'm unclear on whether `/obj/machinery/playerzoldorf` could reasonably exist at startup, so this may be a non-issue, but moving them to `New` isn't going to be a problem in either case.

https://hackmd.io/@goonstation/docs/%2F%40goonstation%2Fcode#StartupRuntime-trade-offs-with-lists-and-the-hidden-init-proc

File: code/obj/zoldorf.dm [hunk 15]
```diff
@@ -85,6 +40,113 @@ var/global/list/datum/zoldorfitem/zoldorf_items = list()
...
+						purchasing = product
+				if(!istype(purchasing, /datum/zoldorfitem/credit))
+					return
+				if ((purchasing.stock <= 0) && !purchasing.infinite)
+					return
+				if(purchasing.price > src.credits)
+					boutput(ui.user, SPAN_ALERT("[src.name] stares blankly into your soul...begging you for more credits..."))
+					return
+				src.credits -= purchasing.price
+				purchasing.stock -= 1
```
Comment (mordent-goonstation) [inline code/obj/zoldorf.dm:102]: Don't decrement if infinite.

File: code/obj/zoldorf.dm [hunk 16]
```diff
@@ -85,6 +40,113 @@ var/global/list/datum/zoldorfitem/zoldorf_items = list()
...
+				purchasing.on_bought(ui.user)
+				return TRUE
+
+	ui_interact(mob/user, datum/tgui/ui)
+		ui = tgui_process.try_update_ui(user, src, ui)
+		if(!ui)
+			ui = new(user, src, "ZoldorfPlayerShop", src.name)
+			ui.open()
```
Comment (mordent-goonstation) [inline code/obj/zoldorf.dm:110]: This is at the wrong indent level, I think.

File: code/obj/zoldorf.dm [hunk 17]
```diff
@@ -85,6 +40,113 @@ var/global/list/datum/zoldorfitem/zoldorf_items = list()
...
+			))
+		for(var/datum/zoldorfitem/credit/product as anything in src.credit_items)
+			products += list(list(
+				"name" = product.name,
+				"stock" = product.stock,
+				"infinite" = product.infinite,
+				"img" = product.img,
+				"price" = product.price,
+			))
+		.["products"] = products
```
Comment (mordent-goonstation) [inline code/obj/zoldorf.dm:135]: It's a decently finite list and quite a niche object so this shouldn't be a massive issue, but if possible I would look to move the products list generation to `ui_static_data` and then call the relevant update proc whenever stock changes.

**Review by mordent-goonstation — CHANGES_REQUESTED** [review]
Reviewed non-tgui changes as well.

File: code/obj/zoldorf.dm (hunk 15 above)
Comment (pgmzeta) [reply code/obj/zoldorf.dm]: changed in the soul portion as well

File: code/obj/zoldorf.dm (hunk 17 above)
Comment (pgmzeta) [reply code/obj/zoldorf.dm:140]: Moved all product data to static and called `src.update_static_data(ui.user)` whenever the product count changes. credit/soul% are still in ui_data.

File: tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx (hunk 12 above)
[the remark this answers is not in the document]
Comment (pgmzeta) [reply tgui/packages/tgui/interfaces/ZoldorfPlayerShop/index.tsx]: added with comments for future clarity

**Review by mordent-goonstation — APPROVED** [review]

**Comment by mordent-goonstation** [comment]
!merge_upstream
