### PR TITLE
TGUI Camera Viewer / Television

### LINKED ISSUE #13135: View gets stuck in Camera mode if Camera Console gets disassembled while using
### Labels

[BUG][MINOR]

### Description

If a person watches cameras from say Security Cameras console and the console gets disassembled the person canot get out of camera view or change cameras

### Steps to reproduce

1. View stuff on cameras through console (in my case was as a borg)
2. Another person disassembles the console
3. I get stuck in camera view, can't close, can't swap cameras, camera control UI does nothing

### Expected Behavior

Either the menu functions contunue working and you are able to close out of cameras or the console forcibly kicks you after being deconned

### Additional Information & Screenshots

Reported by: Ormakent
On server: Goonstation 1 Classic: Heisenbee
Round log date: 2023-02-19-20-10
Reported on: 2023-02-19 20:49:16
Map: COGMAP

### LINKED ISSUE #16953: Stuck in security cam hell.
### Labels

[BUG]

### Description

after closing the cams manu with the [x], you are stuck on your last cam

### Steps to reproduce

1.(not sure if related) having the room burn)
2. when closing the cam list you are stuck on the cam you were on before closing the list.

### Expected Behavior

when pressing the [X] you will return to viewing yourself

### Additional Information & Screenshots

stuff that DON'T fix your view:
-restarting and or reconnecting
-being sent to cryo
-moving

stuff that DOfix the view:
-getting the cam cut with wire cutters (fixing it after that will have no negative effect)

stuff not tested:
-removing the cam
-dying
-destroying the console used to view the cam

### LINKED ISSUE #17042: Camera Stuck
### Labels

[BUG][MINOR]

### Description

Camera is stuck

### Steps to reproduce

1. Use security camera computer.
2. Close the window.
3. Camera being view does not close.
4. Reloading client does not fix issue.

### Expected Behavior

Camera should return to player

### Additional Information & Screenshots

Reported by: Azurnite
On server: Goonstation 3 Roleplay: Morty
Active test merges: #16370
Round log date: 2023-11-22-03-26
Reported on: 2023-11-22 04:27:05
Map: COGMAP

### LINKED ISSUE #19122: Security Camera window keeps closing
### Labels

[BUG][MINOR]

### Description

Every time I try to use the security camera computer, the window opens up and closes itself after a second.

### Steps to reproduce

Click on the security camera computer

### Expected Behavior

The security camera window would stay open

### Additional Information & Screenshots

Reported by: Punchman
Client version: 515.1639
On server: Goonstation 4 Roleplay: Sylvester
Active test merges: #18978
Round log date: 2024-05-24-02-01
Reported on: 2024-05-24 02:25:55
Map: KONDARU

### LINKED ISSUE #19223: Got locked into security camera view with no HUD
### Labels

[BUG][MINOR]

### Description

Well, using the security camera leaves you with no camera HUD and you can't move around after the first view

### Steps to reproduce

1. Use the security cameras
2. Click on a camera to view
3. The camera HUD dissapears and you can't move anymore

### Expected Behavior

Well, for the HUD to not go on vacation

### Additional Information & Screenshots

Thankfully there is the cancel camera view command to exit the out of body experience

Reported by: Steiniumeor
Client version: 515.1639
On server: Goonstation 3 Roleplay: Morty
Active test merges: #19183
Round log date: 2024-05-30-07-50
Reported on: 2024-05-30 08:40:32
Map: KONDARU

### LINKED ISSUE #19667: Security Cameras bug
### Labels

[BUG][MAJOR]

### Description

Whenever I click on security cameras, the window closes after a few seconds. 

### Steps to reproduce

1. Click on security camera to check a camera
2. after a few seconds the window closes for no apparent reason.

### Expected Behavior

I expect the window not to close whenever I'm trying to check it

### Additional Information & Screenshots

had another person test this out too, same thing happened to them. 

Reported by: lopdopgop
Client version: 515.1639
On server: Goonstation 4 Roleplay: Sylvester
Active test merges: #19063
Round log date: 2024-06-24-01-55
Reported on: 2024-06-24 02:18:40
Round ID: 182039
Map: DONUT2

### LINKED ISSUE #21769: Windows keep closing on their own. Cannot use security cameras
### Labels

[BUG][MAJOR]

### Description

Windows keep closing on their own. Cannot use security cameras as a result. Stuck in the security camera view with no option to return the camera

### Steps to reproduce

1. Open any window ie. security camera, hotkeys, etc
2. Window closes
3. Unable to use the menus for more than 3 seconds. Also, get stuck in the secutiry camera view

### Expected Behavior

The windows should stay open

### Additional Information & Screenshots

Reported by: thimb0
Client version: 515.1639
On server: Goonstation 4 Roleplay: Sylvester
Active test merges: #21006, #20620, and #21509
Round log date: 2024-12-20-11-50
Reported on: 2024-12-20 12:52:16
Round ID: 195730
Map: KONDARU

### LINKED ISSUE #22525: stuck on camera
### Labels

[BUG][MINOR]

### Description

closed the window to camera,still seeing camera,cant see self

### Steps to reproduce

1.get on security camera
2.switch cameras back and forth
3.close camera list window
4.stuck on the camera

### Expected Behavior

to be able to see myself and not be stuck

### Additional Information & Screenshots

Reported by: skillzhub
Client version: 515.1641
On server: Goonstation 4 Roleplay: Sylvester
Active test merges: #22466, #22521, and #21781
Round log date: 2025-03-08-17-14
Reported on: 2025-03-08 18:26:46
Round ID: 201707
Map: COGMAP

### LINKED ISSUE #23077: Security Camera viewer screen disappears after only a few seconds
### Labels

[BUG][MINOR]

### Description

When entering the camera view screen via the terminal, the window closes after only a few seconds making it impossible to view any cameras

### Steps to reproduce

Attempt to open the camera viewer window by using a security camera viewer
Have the window close inexpertly after a few seconds

### Expected Behavior

The camera viewer window should not close automatically

### Additional Information & Screenshots

Reported by: gamercake
Client version: 516.1660
On server: Goonstation 4 Roleplay: Sylvester
Active test merges: #22547
Round log date: 2025-04-21-07-56
Reported on: 2025-04-21 08:09:48
Round ID: 204275
Map: COGMAP

### PR DESCRIPTION
**Pull request by pgmzeta**
[rework][ui][station systems]
## About the PR 
Adopt of #22304

Replaces the CHUI camera viewer with a TGUI version featuring a minimap.

There are a few lost features from the CHUI version, to be re-implemented:
* Favorite cameras
* Camera "D-Pad" for moving between cameras
* WASD/arrow key movement
* Setting a viewport window

Repaths `/obj/machinery/computer/security` and its subtypes to two separate paths:
* `/obj/machinery/computer/camera_viewer` with a minimap
* `/obj/machinery/computer/television` with just a list of cameras

Televisions get a list of cameras to connect to, similar to the hand-held camera viewer. The reason for the separate implementation is to prevent minimap bloat for lots of small camnets, and allow for azone camnets to work without a minimap.

## Why's this needed? 
516 compat (CHUI deprecation)
Fix #23077
Fix #22525
Fix #21769
Fix #19667
Fix #19223
Fix #19122
Fix #17042
Fix #16953
Fix #13135

## Screenshot
image

## Changelog 

```changelog
(u)Garash & glowbold
(*)Security camera computers use a minimap to display camera locations
(+)Televisions show a list of available cameras.
```

### CODE REVIEW

File: tgui/packages/tgui/interfaces/CameraViewer.tsx [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+import { MinimapControllerData, MinimapMarkerData } from './MinimapController';
+
+export const CameraViewer = () => {
+  const { data, act } = useBackend<MinimapControllerData>();
+  const { title, theme, minimap_id, minimap_markers } = data;
+
+  return (
+    <Window title={title} theme={theme} width={950} height={700}>
+      <Window.Content>
+        <Stack justify="center">
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/CameraViewer.tsx:22]:
```suggestion
        <Stack>
```
If I'm reading correctly, justify shouldn't be needed.

File: tgui/packages/tgui/interfaces/CameraViewer.tsx [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+};
+
+const MinimapIconMarker = (markerData: MinimapMarkerData) => {
+  const { act } = useBackend<MinimapControllerData>();
+  return (
+    <Stack>
+      <Stack.Item>
+        <Button
+          className="minimap-controller__buttons"
+          icon={'eye'}
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/CameraViewer.tsx:95]:
```suggestion
          icon="eye"
```
World's most trivial nitpick award goes to...

File: tgui/packages/tgui/interfaces/CameraViewer.tsx [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+            act('view_camera', {
+              target_ref: markerData.target_ref,
+            })
+          }
+        />
+      </Stack.Item>
+      <Stack.Item grow>
+        <Flex className="minimap-controller__marker-list" height={3}>
+          <Flex.Item inline>
+            <Flex.Item fontSize={1.1} bold>
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/CameraViewer.tsx:106]:
```suggestion
            <Flex.Item bold>
```
Prefer not subtly increasing font size for purposes of emphasis, leads to a lot of aesthetic preference inconsistency across UIs.

**Review by mordent-goonstation — APPROVED** [review]
TGUI only review:

I feel like refactoring out this kind of viewer into a standard component is worthwhile, as we use it for the general alert one as well I think? Not mandating for this PR as I understand the goal is to get 516 compat up and to kill CHUI. Comments below would apply to the other viewer as well, I think, though I didn't look at extensively.

Approving for the sake of "get this in", would prefer the work was done to tidy this up ASAP.

**Review by TobleroneSwordfish — CHANGES_REQUESTED** [review]
This doesn't appear to work, testing on Atlas the bar computer claims it's not connected to any cameras and the detective's computer brings up a `tgui_input_list`

**Comment by pgmzeta** [comment]
> This doesn't appear to work, testing on Atlas the bar computer claims it's not connected to any cameras and the detective's computer brings up a `tgui_input_list`

There are no public cameras on Atlas; if you spawn in e.g. a television camera it will show that.

Detectives have TVs, not camera viewers. so show the list of cameras instead of the new UI. The camera vieer computer in security appears to be working in my testing (currently using 516)

**Comment by TobleroneSwordfish** [comment]
Oough okay of course those are different
