### PR TITLE
Fix some paper bugs

### LINKED ISSUE #20820: Underscores cause TermOS syntax error when using paper
### Labels

[BUG][MINOR]

### Description

Trying to use underscores to italicise text when writing on paper causes a TermOS syntax error.

### Steps to reproduce

1: Get pen and paper
2: Attempt to write "_Test_"
3: Be jumpscared as the paper bluescreens

### Expected Behavior

Italic text on the paper.

### Additional Information & Screenshots

Reported by: captainrora
Client version: 515.1636
On server: Goonstation 4 Roleplay: Sylvester
Active test merges: #20547 and #20717
Round log date: 2024-09-23-08-02
Reported on: 2024-09-23 09:18:04
Round ID: 188956
Map: CLARION

### LINKED ISSUE #20838: Editing clipboard papers
### Labels

[BUG][MINOR]

### Description

Papers inside a clipboard

### Steps to reproduce

Clipboard paper edit window looses focus upon hitting enter.

### Expected Behavior

Should go to a new line

### Additional Information & Screenshots

Reported by: ncduve
Client version: 515.1637
On server: Goonstation 3 Roleplay: Morty
Active test merges: #20547
Round log date: 2024-09-23-23-37
Reported on: 2024-09-24 00:02:59
Round ID: 189004
Map: DONUT3

### PR DESCRIPTION
**Pull request by ZeWaka**
## About the PR 

Fixes signing in input fields
Fixes marked crashing with es2018 regex
Fixes enter not putting a newline in paper

## Why's this needed? 

fixes #20820
fixes #20838

### CODE REVIEW

File: tgui/packages/tgui/interfaces/PaperSheet/index.tsx [hunk 1]
```diff
@@ -241,6 +236,15 @@ const PaperSheetEdit: React.FC<PaperSheetEditProps> = ({
   const [textAreaText, setTextAreaText] = useState('');
   const [combinedText, setCombinedText] = useState(value || '');
   const [showingHelpTip, setShowingHelpTip] = useState(false);
+  const [remarkable] = useState<Remarkable>(() => {
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/PaperSheet/index.tsx:239]: If no setting, is this actually a `useState`? `useMemo`? If not intended to change as deps change, `useRef`?

File: tgui/packages/tgui/interfaces/PaperSheet/index.tsx [hunk 2]
```diff
@@ -304,6 +308,18 @@ const PaperSheetEdit: React.FC<PaperSheetEditProps> = ({
     }
   };
 
+  const onKeyDownHandler = (event: React.KeyboardEvent<HTMLDivElement>) => {
+    if (event.key === 'Enter') {
```
Comment (mordent-goonstation) [inline tgui/packages/tgui/interfaces/PaperSheet/index.tsx:312]: tgui-core has constants for keys. https://github.com/tgstation/tgui-core/blob/main/lib/common/keys.ts

File: tgui/packages/tgui/interfaces/PaperSheet/index.tsx (hunk 1 above)
Comment (ZeWaka) [reply tgui/packages/tgui/interfaces/PaperSheet/index.tsx:240]: cringe
